### PR TITLE
Update registrationpage.php

### PR DESCRIPTION
**Pull request by Bilal101**
added server side functionality to the page

### CODE REVIEW

**Comment by PaulMicu** [comment]
looks like it adds it proprely but it stays on rerequest.php so that's an issue

**Comment by Bilal101** [comment]
It works good on my side redirect to sign up page so user can sign up

**Comment by PaulMicu** [comment]
ok issue was fixed. php header was after the echo. it won't work like that. instead we will use the HTML equivalent: windows.location

**Comment by PaulMicu** [comment]
this pull request fixes issues #56 #47 and #42

**Pull request merged**
