### PR TITLE
Registration Form HTML AND CSS File

### PR DESCRIPTION
**Pull request by Bilal101**
Html and Css file for registration page need some edits before finalization .

### CODE REVIEW

**Comment by PaulMicu** [comment]
put the files in the correct folder

**Review by PaulMicu — CHANGES_REQUESTED** [review]
is this a duplicated pull request??

**Comment by Bilal101** [comment]
Yes this is old request , please ignore it .

**Comment by PaulMicu** [comment]
ok please dont do more than 1 pull request for the same issue

**Pull request closed without merging**
