### PR TITLE
Best answer

### PR DESCRIPTION
**Pull request by PaulMicu**
the website should display the best answer slightly differently and the owner of the post should be able to favourite any number of comments. the best answer is the answer with the most likes and the favourite is an image next to the name for aesthetic purposes only

### CODE REVIEW

**Comment by PinMeister** [comment]
Change "v" to "comment" on line 120 of viewPost.php

**Comment by PinMeister** [comment]
image
Variable "user_id" undefined in viewPostAction.php whenever there is no user signed in.

**Comment by PinMeister** [comment]
Please remove random apostrophe (`) from line 53 of viewPost.php

**Comment by PaulMicu** [comment]
thanks @PinMeister il fix that asap

**Comment by PaulMicu** [comment]
@PinMeister  issue fixed, will commit master

**Pull request merged**
